version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - BASE_URL=http://localhost:8080
      - DOMAIN=
      - API_KEY=${API_KEY:-your_secure_api_key_here}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=urlshortener
      - DB_SSL_MODE=disable
      - URL_LENGTH=6
      - RATE_LIMIT=100
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - url-shortener-network

  postgres:
    image: postgres:15-alpine
    container_name: url-shortener-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=urlshortener
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - url-shortener-network

volumes:
  postgres-data:

networks:
  url-shortener-network:
    driver: bridge 
